const NEW_VERSION = "NEW_VERSION",
      DOWNLOADING = "DOWNLOADING",
      INSTALLING = "INSTALLING",
      SWAPPING = "SWAPPING",
      RESTARTING = "RESTARTING";


exports.NEW_VERSION = NEW_VERSION;
exports.DOWNLOADING = DOWNLOADING;
exports.INSTALLING = INSTALLING;
exports.SWAPPING = SWAPPING;
exports.RESTARTING = RESTARTING;